package com.atfotiad.composefoundry.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.material3.adaptive.navigationsuite.NavigationSuiteScaffold
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.navigation.NavGraph.Companion.findStartDestination
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import com.atfotiad.composefoundry.designsystem.foundation.theme.FoundryTheme
import com.atfotiad.composefoundry.navigation.Destinations
import com.atfotiad.composefoundry.navigation.getIcon // We will create this
import com.atfotiad.composefoundry.navigation.getLabel // We will create this
import com.atfotiad.composefoundry.ui.theme.BrandLightScheme
import com.atfotiad.composefoundry.ui.theme.BrandTypography

@Composable
fun AppContent(
    uiState: MainUiState,
) {
    when (uiState) {
        is MainUiState.Loading -> {
            Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                CircularProgressIndicator()
            }
        }

        is MainUiState.Success -> {
            FoundryTheme(
                colorScheme = BrandLightScheme,
                typography = BrandTypography,
                dynamicColor = false,
                darkTheme = uiState.isDarkTheme
            ) {
                val navController = rememberNavController()
                val navBackStackEntry by navController.currentBackStackEntryAsState()
                val currentRoute = navBackStackEntry?.destination?.route

                // 🪄 Adaptive Shell: Handles BottomBar (Mobile) vs NavRail (Tablet)
                CompositionLocalProvider(LocalNavController provides navController) {
                    NavigationSuiteScaffold(
                        navigationSuiteItems = {
                            // Destinations.topLevelItems is the list generated by your KSP magic
                            Destinations.topLevelItems.forEach { destination ->
                                item(
                                    selected = currentRoute == destination.route,
                                    onClick = {
                                        navController.navigate(destination.route) {
                                            popUpTo(navController.graph.findStartDestination().id) {
                                                saveState = true
                                            }
                                            launchSingleTop = true
                                            restoreState = true
                                        }
                                    },
                                    icon = {
                                        Icon(
                                            destination.getIcon(),
                                            contentDescription = null
                                        )
                                    },
                                    label = { Text(destination.getLabel()) }
                                )
                            }
                        }
                    ) {
                        AppNavHost(
                            navController = navController,
                            startRoute = uiState.startDestination
                        )
                    }
                }
            }
        }
    }
}
